### ISSUE TITLE
Error responses for invalid resources

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-provider-testing#261] opened 2019-05-29 13:22 UTC
The following tests are currently looking for a 400/BAD_REQUEST error response, but 422/INVALID_RESOURCE is more accurate according to the following spec page - https://developer.nhs.uk/apis/gpconnect-1-2-3/development_fhir_error_handling_guidance.html

```
GPConnect.Provider.AcceptanceTests.AppointmentBookFeature.BookAppointmentForPatientAndSendExtraFieldsInTheResource
GPConnect.Provider.AcceptanceTests.PatientRegisterFeature.RegisterPatientWithAdditionalNotAllowedElements("Animal",System.String[])
GPConnect.Provider.AcceptanceTests.PatientRegisterFeature.RegisterPatientWithAdditionalNotAllowedElements("Communication",System.String[])
GPConnect.Provider.AcceptanceTests.PatientRegisterFeature.RegisterPatientWithAdditionalNotAllowedElements("Deceased",System.String[])
GPConnect.Provider.AcceptanceTests.PatientRegisterFeature.RegisterPatientWithAdditionalNotAllowedElements("Photo",System.String[])
GPConnect.Provider.AcceptanceTests.PatientRegisterFeature.RegisterPatientWithInvalidAdditionalValidElements("Active",System.String[])
GPConnect.Provider.AcceptanceTests.PatientRegisterFeature.RegisterPatientWithInvalidAdditionalValidElements("Births",System.String[])
GPConnect.Provider.AcceptanceTests.PatientRegisterFeature.RegisterPatientWithInvalidAdditionalValidElements("CareProvider",System.String[])
GPConnect.Provider.AcceptanceTests.PatientRegisterFeature.RegisterPatientWithInvalidAdditionalValidElements("Contact",System.String[])
GPConnect.Provider.AcceptanceTests.PatientRegisterFeature.RegisterPatientWithInvalidAdditionalValidElements("ManagingOrg",System.String[])
GPConnect.Provider.AcceptanceTests.PatientRegisterFeature.RegisterPatientWithInvalidAdditionalValidElements("Marital",System.String[])
GPConnect.Provider.AcceptanceTests.PatientRegisterFeature.RegisterPatientWithInvalidPatientResourceWithAdditionalElement

```

**Comment by SimonFarrowNHS** [comment] 2019-06-17 15:16
I am querying the last entry on the list above. I cant find a test named:
GPConnect.Provider.AcceptanceTests.PatientRegisterFeature.RegisterPatientWithAdditionalNotAllowedElement

**Comment by PeterGresty** [comment] 2019-06-18 07:03
Last Entry in list is a duplicate of one further up that appears to have been truncated.. ignoring last entry.

**Comment by SimonFarrowNHS** [comment] 2019-06-18 09:50
Removed erroneous last entry

**Comment by PeterGresty** [comment] 2019-08-19 10:11
Code Release, tickets can be clsoed

**Closed by PeterGresty** 2019-08-19 10:11 UTC
Labels: 1.2.3, Appointments, Automated test, Foundations
